terminate called after throwing an instance of 'std::runtime_error'
  what():  UnaryFunctionInvocation::code_gen is not implemented.
